version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-mycollab:
    image: bibbox/mycollab
    container_name:  §§INSTANCE-mycollab
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-mycollab-db:mycollab-db
    ports:
      - "§§PORT:80"
    depends_on:
      - §§INSTANCE-mycollab-db
      - §§INSTANCE-mycollab-data
    volumes_from: 
      - §§INSTANCE-mycollab-data

  §§INSTANCE-mycollab-db:
    image: mysql:5.7.17
    container_name: §§INSTANCE-mycollab-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=mycollab
      - MYSQL_USER=mycollab
      - MYSQL_PASSWORD=mycollab4bibbox
    volumes_from: 
      - §§INSTANCE-mycollab-data
    depends_on:
      - §§INSTANCE-mycollab-data

  §§INSTANCE-mycollab-data:
    image: busybox
    container_name: §§INSTANCE-mycollab-data
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
